version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: install_node.sh
      timeout: 60
      runas: root
    - location: install_dependencies.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: start_app.sh
      timeout: 300
      runas: root
