version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/install_node.sh
      timeout: 60
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
