version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "installing nodejs"
      - sudo su
      - yum install nodejs -y
      - node -v
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building application"
      - node app

cache:
  paths:
    - 'node_modules/**' # Cache dependencies for faster builds
